// Test definitions. Do NOT edit this file!

#include <tuple>

#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch_amalgamated.hpp"

#include "../Celular.hpp"


// =====================
// tests para Examen Celular
// ---------------------

TEST_CASE("Ex1", "[Probando constructor default de Bateria]")
{
    Bateria amigo;
    SECTION("Verificando sus atributos default de Bateria")
    {
        REQUIRE(amigo.getVoltaje() == 6.5);
        REQUIRE(amigo.getMarca() == "Patito");
    }
}

TEST_CASE("Ex2", "[Probando constructor con parametros de Bateria]")
{
    Bateria amigo(-3, "Sanson");
    Bateria amigo2(9, "Dalila");
    SECTION("Verificando creacion con parametros en Bateria")
    {
        REQUIRE(amigo.getVoltaje() == 6.5);
        REQUIRE(amigo.getMarca() == "Sanson" );
        REQUIRE(amigo2.getVoltaje() == 9);
    }
}

TEST_CASE("Ex3", "[Probando setters de Bateria]")
{
    Bateria nueva;
    Bateria otra;
    SECTION("Verificando cambios en los atributos de Bateria")
    {
        nueva.setVoltaje(5);
        nueva.setMarca("Otra");
        otra.setVoltaje(12);
        REQUIRE(nueva.getVoltaje() == 6.5);
        REQUIRE(nueva.getMarca() == "Otra");
        REQUIRE(otra.getVoltaje() == 12.0);
    }
}

TEST_CASE("Ex4", "[Probando Imprimir]")
{
    Bateria f1(7,"Sensacional");
    SECTION("Mostrando en consola los datos de la Bateria")
    {
        f1.imprime();
        REQUIRE(true);
    }
}

TEST_CASE("Ex5", "[Probando iguales de Bateria]")
{
    Bateria f1(10,"Exa");
    Bateria f2(6.5,"Patito");
    Bateria f3;
    SECTION("Probando iguales")
    {
        REQUIRE(f1.iguales(f3)==0);
        REQUIRE(f3.iguales(f2)==1);
    }
}

TEST_CASE("Ex6", "[Constructor Default de Celular]")
{
    Celular c1;
    SECTION("Constructor Default")
    {
        Bateria f1;
        REQUIRE(c1.getModelo()=="Iphone10");
        REQUIRE(c1.getMarca()=="Apple");
        REQUIRE(c1.getBateria().iguales(f1)==1);
    }
}

TEST_CASE("Ex7", "[Constructor con parámetros de Celular]")
{
    Celular c2("XXW", "MARCA", Bateria(11.5,"Blanca"));
    SECTION("Constructor con parámetros de Celular")
    {
        Bateria f2(11.5, "Blanca");
        REQUIRE(c2.getModelo()=="XXW");
        REQUIRE(c2.getMarca()=="MARCA");
        REQUIRE(c2.getBateria().iguales(f2)==1);
    }
}

TEST_CASE("Ex8", "[Probando setters]")
{
    Bateria f3(9.0,"Ideal");
    Celular c3;
    SECTION("Setters de Celular")
    {
        c3.setModelo("Pikachu");
        c3.setMarca("Chamoy");
        c3.setBateria(f3);
        REQUIRE(c3.getModelo()=="Pikachu");
        REQUIRE(c3.getMarca()=="Chamoy");
        REQUIRE(c3.getBateria().iguales(f3)==1);
    }
}


TEST_CASE("Ex9", "[Probando imprime de Celular]")
{
    Celular c4;
    SECTION("Imprime de Celular")
    {
        c4.imprime();
        REQUIRE(true);
    }
}